# Generated by Django 5.2.5 on 2025-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0002_rename_creado_en_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='user_id',
            new_name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Jugador', 'Jugador')], max_length=20),
        ),
    ]
