# Generated by Django 5.2.5 on 2025-10-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0003_rename_user_id_jugador_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
