# Generated by Django 5.2.5 on 2025-10-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0004_alter_usuario_email_alter_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
