# Generated by Django 5.2.5 on 2025-10-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0005_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
