# Generated by Django 5.2.5 on 2025-10-20 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0006_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario_palabras',
            new_name='UsuarioPalabras',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='nivel_id',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='palabra',
            old_name='nivel_id',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='evaluacion_id',
            new_name='evaluacion',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='palabra_id',
            new_name='palabra',
        ),
        migrations.RenameField(
            model_name='usuariopalabras',
            old_name='palabra_id',
            new_name='palabra',
        ),
        migrations.RenameField(
            model_name='usuariopalabras',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('ahorcado', 'Ahorcado'), ('pares', 'Pares'), ('union', 'Union')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EvaluacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_semillitas.evaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEvaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=150)),
                ('completado', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_semillitas.evaluacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
