# Generated by Django 5.2.5 on 2025-10-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0007_rename_usuario_palabras_usuariopalabras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciones',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultadoevaluaciones',
            name='puntaje',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_semillitas.evaluacion')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_semillitas.palabra')),
            ],
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
