# Generated by Django 5.2.5 on 2025-10-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0008_remove_evaluacion_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
