# Generated by Django 5.2.5 on 2025-10-28 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0011_alter_usuario_password_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopalabras',
            name='palabra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_semillitas.palabra'),
        ),
        migrations.AlterField(
            model_name='usuariopalabras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usuariopalabras',
            unique_together={('usuario', 'palabra')},
        ),
    ]
