# Generated by Django 5.2.5 on 2025-11-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_semillitas', '0012_alter_usuariopalabras_palabra_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ejercicio',
            unique_together={('evaluacion', 'palabra')},
        ),
    ]
